### PR TITLE
File a Duplicate feature 💪

### PR DESCRIPTION
**Pull request by steipete**
This adds a new button that fetches radars from OpenRadar.

It's not pretty, but it works. Feel free to improve my Swift.

If you want to try it and enjoy executing binaries from random internet people, [be my guest 🙃](https://cl.ly/3A1H1R2Z3C1a)

PS: [If you want to learn how to write great bug reports, check out the PSPDFKit blog.](https://pspdfkit.com/blog/2016/writing-good-bug-reports/)

dupe

Matching of Areas could be better (but they also have been updated and need fixing...)

### CODE REVIEW

**Comment by keith** [comment]
Haha, are you trying to have a feature-off with me 😛  https://github.com/br1sk/brisk/pull/75

**Comment by keith** [comment]
You can see on my PR that I actually chose to go down the other path and not parse the openradar summary response. I had an iteration that did that, but was worried it was too error prone, the only weird side effect is that even though it ends up looking the same on radarweb, when you fill the Brisk UI with it, since it only fills a single field, it feels pretty strange.

**Comment by steipete** [comment]
@keith Ha, I wanted this for months, and now we build it within the same day? 🤷‍♂️

**Comment by keith** [comment]
I've just merged https://github.com/br1sk/brisk/pull/75 for the same feature here. Please try it out and let me know if you spot any issues. I ended up parsing the open radar response (at least in the common case). The big exception that I've noticed a few occurrences of on openradar is for radars that don't start with `Summary:` even though they follow the format otherwise. I might add a special case for that if it becomes on issue.

Sorry we ended up doing a bit of duplicate work here!

**Comment by steipete** [comment]
Great work, thanks!

**Pull request closed without merging**
