### PR TITLE
Workaround for #30, #33

### LINKED ISSUE #30: Text areas do not redraw themselves
I'm having an odd issue where the text areas are don't seem to update at all. I can "type" in them (I've confirmed that the relevant delegate methods are being called, and that their text is changing internally), but nothing shows up. Based on this:

screen shot 2017-04-12 at 16 09 15

which was caused by focusing the text field above it a bunch of times, I'm guessing that the text area isn't redrawing itself properly. Oddly enough, adding a new text view in the storyboard seems to fix the issue.

### PR DESCRIPTION
**Pull request by saagarjha**
This is a hack to fix #30 and #33 until Apple fixes rdar://problem/34061891.

### CODE REVIEW

**Comment by keith** [comment]
Thanks for submitting this! I don't see any negative effects so it should be good to go. But first can you remove the update pods commit, I don't want to be on a beta CP version, and also can you fix the indention of the code and comment here? It seems to be a bit off.

**Comment by saagarjha** [comment]
Sure thing.

**Comment by keith** [comment]
Nice thanks! I'll merge it when it's green!

**Comment by saagarjha** [comment]
@keith I've fixed the formatting issues. Is there anything else you'd like me to do?

**Comment by keith** [comment]
Nope sorry, it just took a long time for travis to run

**Pull request merged**
