### PR TITLE
Adds drag-'n-drop support for a single attachment

### PR DESCRIPTION
**Pull request by AndreasVerhoeven**
Not very fancy, but fixes a small annoyance I had by adding simple drag-'n-drop (great tool btw!)

ezgif-2-24fb8ab77d

### CODE REVIEW

**Comment by ZevEisenberg** [comment]
It would be nice if there were some visual indication to let the user know that they can drag in a file, but this is awesome!

**Comment by AndreasVerhoeven** [comment]
@ZevEisenberg agreed - that would require some rework on the UI I think. I think it makes sense to directly add support for multiple attachments as well. I would be fine doing that, if there are some suggestions for the UI :)

**Comment by unnamedd** [comment]
If I could suggest something related to UI for these issue, take a look into issue  https://github.com/br1sk/brisk/issues/17

**Comment by keith** [comment]
Awesome, thanks for submitting this @AndreasVerhoeven ! I've changed the droppable class a bit to have a bit more of the responsibility and submitted https://github.com/br1sk/brisk/pull/109 so I'm going to close this one.

I think this UI is a good start for now, and we need multiple attachment UI before we do much more with it. Right now this code should be extensible to multiple attachments, we just need to figure out the UI piece before we support that.

**Comment by keith** [comment]
Released in 1.1.0

**Pull request closed without merging**
